name: Bug Report
description: Create a report to help us improve
labels: [bug]
body:
  - type: dropdown
    id: minecraft-version
    attributes:
      label: Minecraft Version
      description: What version of Minecraft are you running? If you do not know what version you are using, look in the bottom left corner of the main menu in game.
      options:
        - 1.20.2
        - 1.17.0
    validations:
      required: true
